# Site settings
title: Makenna Rapien
email: makennarapien@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Professional website of Makenna Jean Rapien
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://shayno527.github.io/makenna-rapien-page/" # the base hostname & protocol for your site
github_username:  Shayno527
twitter_username:

# Build settings
markdown: kramdown

# Other options
#permalink: blog/:year/:month/:title
#job.title: "Department Chair, Professor"
excerpt_separator: "<!--more-->"
